#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 1, binding = 0, rgba8) uniform image2D u_OutputImage;

void main()
{
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageDimensions = imageSize(u_OutputImage);

    // Bounds check to avoid writing out-of-bounds pixels
    if (pixelCoord.x >= imageDimensions.x || pixelCoord.y >= imageDimensions.y)
    {
        return;
    }

    vec2 uv = vec2(pixelCoord) / vec2(imageDimensions - 1);

    vec4 color = vec4(uv.x, uv.y, 0.0, 1.0);

    imageStore(u_OutputImage, pixelCoord, color);
}
